name: ibm_q_sub

channels:
   - conda-forge

dependencies:
  - python=3.9.10
  - matplotlib=3.5.1
  - numpy=1.21.5
  - pandas=1.4.2
  - pytz=2021.3
  - scikit-learn=1.0.2
  - scipy=1.8.0
  - seaborn=0.11.2
  - pip=22.0.4
  - pip:
    - hydra-core==1.1.2
    - 'qiskit[visualization]==0.34.0'
    - xgboost==1.6.0
    - tensorboard==2.8.0
    - tensorboardx==2.5
    - crc32c==2.2.post0
    - jupyter-lsp==1.5.1
    - jupyterlab==3.2.5
    - jupyterlab-git==0.34.0
    - jupyterlab-lsp==3.9.3
    - 'python-lsp-server[all]==1.4.1'
    - ipywidgets==7.6.5
    - black==22.3.0
    - flake8==4.0.1
